### ISSUE TITLE
Background settings

### ISSUE THREAD

**Issue by waraiotoko2501h** [NetNerd/8beatMap#6]
背景の画像を設定できるといいと思います。
I want a can set the background.

**Comment by NetNerd** [comment]
Yes, it probably would be a good feature to add in the future.  
Currently, you can use the "Allow Transparency" option in window capture with the software "OBS" to add a background image (in another source).

そうですね。。　多分未来に実行すると思います。
今は、「OBS」と言うソフトのウインドウキャプチャを使えば、「透過を許可」設定で自分の背景を足せます（他のソースで）。

**Comment by NetNerd** [comment]
This feature has been added now.
Sorry for taking so long.
